# Generated by Django 3.0.5 on 2020-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('standard', models.IntegerField(choices=[(8, '8th'), (9, '9th'), (10, '10th')])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
